# GET 
# Authorization: Basic Authorization
# Content-Type: application/json
# http://localhost:4004/browse/Books
# ;

POST http://localhost:4004/admin/Foo
Content-Type: application/json

{
    "ID":13,
    "name":"avr",
    "age":"11"
}

###

GET http://localhost:4004/admin/Foo
Content-Type: application/json



###

POST http://localhost:4004/admin/Bonus
Content-Type: application/json

{
          "ID"     : 4466,
          "name"   : "saj" ,
          "value"  : "kss",
          "accepted":true
}

